### PR TITLE
Stevewds matlabtoolboxupdates 1

### PR DESCRIPTION
**Pull request by stevewds**
Hi - 

This adds a Live Script demo in Matlab online. 

Due to some peculiarities in the Matlab File Exchange process, I'll need to update the README one more time to link to the viewable output of the Live Script after this is up.

Best
Steve

### CODE REVIEW

**Comment by vijayiyer05** [comment]
Exciting to see! 

@stevewds, somehow the Open in MATLAB Online link (play button) isn't working on my end. Can you check again? 

I realize the view link will have to come after File Exchange updates.

**Comment by stevewds** [comment]
Added a fix in a new pull request, thanks

**Comment by fatihdinc** [comment]
Accepted both! Thank you so much!

Fatih

On Nov 8, 2023, at 4:53 PM, stevewds ***@***.***> wrote:



Added a fix in a new pull request, thanks

**Comment by vijayiyer05** [comment]
Excellent, just ran EXTRACT in MATLAB Online. An historic day!

One last (promise!) suggestion: turn the visualize_cellfinding to true/1. I just tried that. Makes the experience (and live script output) a lot more interesting & informative.

**Comment by stevewds** [comment]
and done! That's a nice change.

**Pull request merged**
